var studentInfo = [
['Aaron Urban', 'philosophy'],
['Alejandra Romero', '\"Within design, the imagination of what you can create with it has no limit. I believe that every designer has a unique mind of their own which is what allows them to be exactly that, a designer. Paul Rand’s definition of design essentially describes what I consider to be the true definition of design. There is no set definition of what design can truly mean or of what it could be for that matter, as Paul Rand once said: \“Design is the method of putting form and content together. Design, just as art, has multiple definitions; there is no single definition. Design can be art. Design can be aesthetics. Design is so simple, that\'s why it is so complicated.\" We are all surrounded by multiple variations of design. This is exactly what I enjoy about being a designer, the freedom I have to create and do things the way I wish to do. Design falls behind creativity where there are no set of rules in which one must follow. That is what makes it so magical and at the same time, almost impossible for everyone to experience it. Design is so much more than a simple aesthetic or a fast car,  it is the fundamental of creating, understanding, and amend the imperfect. Throughout the years design has changed and opened new doors for designers today. It is our own gift turning it into our own responsibility. The beauty about design is that it can be anything but not everything.'],
['Alex Bang', 'philosophy'],
['Alex Inokuchi-Garvin', 'philosophy'],
['Alexis Joseph', 'Excellent design comes from experimentation through the different disciplines of design. Design is understanding society interactions and impression of their surrounding environment. I have explored different parts of visual communication design that has clear illustration of the world around us ; Design is reflective. When designing, I focus on how I can use universal design so everyone can learn from the information illustrated that is different yet changing the way we understand our changing world.'],
['Alexis De la Torre', 'philosophy'],
['Alyssa Cortez', 'I have always been someone who loves to help and educate people when I can, and thankfully design can be used as a tool to do just that. I love that fact that design can be used deliberately or subliminally to teach something new. I believe design should be used to better the world around us, visually and/or educationally. Recently, I\'ve become interested in behavioral changes, specifically when it comes to sustainability. As designers, we have the ability to design in or design out old behaviors and replace them with new, better ones. I am excited to explore sustainable behavioral changes in my senior project and throughout my career as a visual designer.'],
['Ameer Razman Chin', 'My design philosophy: keep it minimal, but impactful. In creating my designs, I hope for my viewers to not only see, but feel, when they interact with my work. Photography is also a main element in my design as I enjoy taking both digital and film photos. Lastly, unlike my monochrome wardrobe, my designs have a more colorful approach.'],
['Amy Lau', 'Creating aesthetic, useful products that can benefit users is my design philosophy. I believe that a good balance of form and function can make a great product. I like to tackle projects using a hands on perspective with users in mind.'],
['Angela Feng', 'philosophy'],
['Angela Gabriel', 'philosophy'],
['Ashley O\'Brien', 'philosophy'],
['Brett McCormack', 'After working in the Nathan Shapira Design Archive I learned to recognize design as a way of thinking rather than a skill or craft.'],
['Brian Liu', 'philosophy'],
['Briana Gardener', 'Briana is a photographer and social media artist focused on art as a means for social action. She\'s interested in how art, media, and communication can be applied intentionally and intelligently to create change. '],
['Calvin Smith', 'philosophy'],
['Carlos Rosas Lopez', 'philosophy'],
['Casey Goldman', 'philosophy'],
['Charlie Pham', 'philosophy'],
['Chayla King', 'philosophy'],
['Chengming Zhang', 'philosophy'],
['Chi ki Foo', 'philosophy'],
['Chongzhou Wang', 'philosophy'],
['Chris Bateman', 'philosophy'],
['Christian Reyes', 'philosophy'],
['Christopher Nguyen', 'philosophy'],
['Christopher Gonzalez', 'philosophy'],
['Cindy Lopez', 'philosophy'],
['Connie Mach', 'philosophy'],
['Connor Dohmen', 'philosophy'],
['Cory Vaile', ' The key to design for me lies in the nuances of everyday problems and reactions to situations. Design is a comprehensive approach to understanding human interactions through researching and developing solutions. Solutions can be inventions, things, ideas, or brands. Once the problem and solution are realized, the reaction is the basis for success. My personal goals when designing are to simplify the problems and address them with as complete a solution as possible. With proper understanding and research of the problem and the audience, the design should naturally fall into place.'],
['Crisanto Dela Pena', 'philosophy'],
['Crystal Candalla', 'philosophy'],
['Dakota Clark', 'philosophy'],
['Daniel Genis', 'philosophy'],
['Daniel Chu', 'philosophy'],
['Daniela Cabezas', 'I was someone that decided to get into the medical field when deciding to go to college but when I started college I noticed that I had a need to express my creativity. I decided to change majors and when I got into the Visual Communications Design program I realized this is where I need to be. My life revolves around this quote by Maya Angelou: "You can’t use up creativity. The more you use, the more you have." Design is in your everyday life. Everywhere you look there is some sort of design, its everywhere! But what most people don\'t know is that these design have a meaning. That\'s what attracted me to design. Once you realize why something was designed a certain way you start to want to pick out the meaning to everything you see in the world. Once you start picking out the meanings of design life is never boring!'],
['Daniela Alcaraz', 'philosophy'],
['David Matthew Sanchez', 'Design is another form of communicating information, feelings, and messages to others. As a designer, I enjoy the process of helping people take their ideas and putting them onto screens. All designers are different because we all see the world in different ways, and get to share our unique perspectives through our work.'],
['Dean Cohen', 'philosophy'],
['Delmy Cordon', 'philosophy'],
['Devan Ponce', '"One of the most valuable lessons I have learned while obtaining my anthropology degree is the value of empathy. Without empathy one is limited in understanding the human experience or even one’s self. My design philosophy would be centered around empathy as a tool for effective human centered design. “Future Designers must concern themselves with the Quality of Life and not merely the decorative arts.” -Nathan Shapira"'],
['Dezza Vidrio', 'philosophy'],
['Dominika Laukova', 'philosophy'],
['Edilson Diaz', '"Design is everything around us, although a lot of people might not look at it from that perspective, all the products that surround us were once designed by someone and I see that as very impactful and powerful, in other words, we designers design and shape the world for other people. And that is what motivates me to always move forward to continue expanding and improving my design skills to better serve my community and design better products that will improve our lives and shape our future.  

"'],
['Edward Bond', 'philosophy'],
['Elaina Keegan', 'philosophy'],
['Esther Chin', 'philosophy'],
['Fernando Maldonado', 'philosophy'],
['Francisco Tapia', 'philosophy'],
['Gabriela Pasquini', 'philosophy'],
['Gabrielle Kop', 'philosophy'],
['Hayden Wolf', 'philosophy'],
['Iversander Marroquin', 'philosophy'],
['Jack Tenley', 'philosophy'],
['Jake Smit', 'philosophy'],
['Jason Appler', 'philosophy'],
['Jasper Salomon', 'philosophy'],
['Jaynie Angelique Batin', 'philosophy'],
['Jenna M. Stamm', 'I knew I wanted to go into design when I heard Chip Kidd describe himself as a problem-solver. Since then, and throughout my 2 years at SFSU\'s School of Design, I have been searching for solutions within the problems of each project, looking for answers in the [sometimes] seemingly endless ideations and iterations—the sign in the design. As hard as it may be, I have learned that, to trust in the process, is to create art that is purposeful and whose intent is clear.'],
['Jesse Vo', 'philosophy'],
['Jessica Noriega', 'philosophy'],
['Jesus Calderon', 'philosophy'],
['Jesus Negrete', 'philosophy'],
['Johnathon Tott-Berger', 'User–Centered–Design and Analog–Still–Rules are my design philosophies. Good design is not done simply with one person at a desk cranking out products, it is a process that involves interaction between people, it places the user at the center of design and utilizes the users input to help shape the final outcome of any given product. In this sense you are not designing something for yourself, rather you are designing something for the greater good of the world and that\'s really amazing. Analog tools and skills are the foundation for which digital tools and skills derived. I enjoy being hands–on with my work and practice stepping away from the computer to design; when I do, I find it quicker to iterate and visualize the strengths and weaknesses of the design at different phases. '],
['Jonathan Ogata', 'philosophy'],
['Jonathan Camacho', 'Design is all about moving forward and finding the right solutions. My favorite quote is from a designer named Paul Rand, "The designer does not begin with a preconceived idea. Rather, the idea is the result of careful study and observation and the design a product of that idea".'],
['Jonny Ogata', 'philosophy'],
['Juliana Cacciaroni', 'philosophy'],
['Karina Zalac', 'I value careful organization, conscientious planning, thoughtful time management, and user-centered design. One of my favorite quotes about design is by Micha Commeren who states, \"The function of design is letting design function.\" I strive to design solutions that clearly communicate to the viewer and also make a rememberable impact.'],
['Katherine Berg', 'philosophy'],
['Kenny Ngo', 'For me, design is summed up in a single quote by Antoine de Saint-Exupéry, "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away." Although I\'ve been this program for quite a while, I never truly understood what it meant to be a designer with a capital \'D\', as professor Kaminska always said. I\'ve always placed too much effort in designing despite not having a good foundation or an eye for it, but being in this major has allowed me to grow for the best. I\'ve learned that by highlighting everything, I\'ve highlighted nothing, and in this case, design is more-so a "less is more" situation.'],
['Kevin Lambert', 'Since industrializing, society has called for designers to optimize our lifestyles with products and infrastructure, inexorably tying design to the ever-growing economy until modern disruptions like resource shortages, the mounting Climate crisis, and Coronavirus pandemic added some much needed nuance to the narrative. My design philosophy builds on sustainability tropes of the 80\'s: Resilience is the single most important element of good design today. As explained on UXDesign.cc, to be resilient, all aspects of a product\'s life cycle must be assessed for environmental impact, the design itself must be hardy, resistant to damage and obsolescence, and above all human needs must be balanced fairly with the planet\'s. Resilient design principles overlap with sustainability but incorporate a realistic view of society\'s industrial impact and seek to adapt to, some view as unavoidable, shortages, economic shocks, and environmental hazards in our future.'],
['Khang Hoang', 'philosophy'],
['Korina Moreno', 'philosophy'],
['Kristy Chi', 'philosophy'],
['Kwanwu Yu', 'philosophy'],
['Kyle Millhollin', 'philosophy'],
['Lauren Pattugalan', 'philosophy'],
['Lauren Hohls', 'philosophy'],
['Leilani Paz', 'philosophy'],
['Lemuel Manalo', 'philosophy'],
['Linda Lueng', 'philosophy'],
['Lois Chen', 'philosophy'],
['Madison Macha', 'philosophy'],
['Mahya Lewis', 'philosophy'],
['Mariana De Araujo Souto', 'philosophy'],
['Mariantonia Cambareri', '\"I see graphic design as the organization of information that is semantically correct, syntactically consistent and pragmatically understandable. I like it to be visually powerful, intellectually elegant and, above all, timeless.\" Massimo Vignelli, Over the years, since I entered the world of graphics, the example of Massimo Vignelli has been of fundamental importance. I like his concept of design as a single thing. A single entity that is conveyed through various projects, but that needs the same type of approach for each of them. I like to think I can design with order and discipline, create something with a meaning and without time, always trying to be responsible and respectful strongly believing that design is also a passion.'],
['Marielle Cabillo', 'philosophy'],
['Mary Motley', 'philosophy'],
['Mattie Nye', 'philosophy'],
['Mauricio Morazan Mejia', 'When I think about design is to approach to a problem-solving that applies to cognitive activities of design thinking, what inspired me about design is about communication on what I would like to say on my design and the message I would like to share to other based on my work, what motivates me to be a designer is because from my family who support me on each step to reach my goals and I would be always thankful to my parents.'],
['Max Kolden', 'philosophy'],
['Maxwell Lohr', 'philosophy'],
['Mia Dong', 'philosophy'],
['Michael Ihle', 'Design is what you make it, literally. The \'standard\' for good design was chosen by those leading in the field, but that doesn\'t mean it is the only kind of design. Create what you enjoy, and what you consider to be good. Make the new standard, challenge yourself, and push the boundaries of what design could be.'],
['Michelle Nam', 'philosophy'],
['Monica Chum', 'Design is always about the user. If at any point, a piece is designed without the audience in mind, it isn\'t good design, even if it looks pretty. The design also has to be functional, useful, appropriate, and visually appealing to the specific user. One cannot exist without the rest.'],
['Natasha Sherbaf', 'philosophy'],
['Nicolas Noratto', 'philosophy'],
['Nik Dommen', 'philosophy'],
['Niklaus Dommen', 'philosophy'],
['Noah Castro', 'philosophy'],
['Nora Kettles', 'philosophy'],
['Omar Hernandez', 'philosophy'],
['Pablo Wu', 'philosophy'],
['Pamela Liutama', 'philosophy'],
['Paramveer Singh', 'philosophy'],
['Rachel Ward', 'philosophy'],
['Regine Ong', 'philosophy'],
['Rexford Adams', 'philosophy'],
['Roberto Berrocal-Pujol', '"Since high school I knew that I was some sort of an artist and it wasn\'t until my sophomore year in ""Fine Arts with an emphasis in Graphic Design"" that I discovered my niche in ""Product Design"", so I switched majors. Soon after joining the Mankind Project I discovered my life\'s mission: -Create a world of balance, harmony and abundance by designing tools of creation-. More recently I\'ve switched majors to ""Industrial Design"", thus my journey.Roberto Berrocal - Pujol currently attends San Francisco State University, pursuing a degree in Industrial and Product Design."'],
['Ryan Bach', 'philosophy'],
['Ryan Spalding', 'philosophy'],
['Sabrina Umbay', 'philosophy'],
['Samuel Vasquez', 'philosophy'],
['Sarina Campanella', '"Design is a form of art. ""To create art is not to preach or make a statement, it is to communicate. And communication is an exchange of thought between two or more minds. Creating art therefore brings humans together in the deepest way."" - Anonymous Design itself is used to bring people together, whether that be through apps, or building a new product, we create to express our passions and to share with others. When I design I feel that I can make a difference, and I feel like my true self when being able to bring my imagination to life. "'],
['Sean Huang', 'My view of design is about the balance of innovation, empathy, and Marketing. Understanding the need of a person, Emphasize and state the problem, and backed by research and data.'],
['Shaine Edmond', 'philosophy'],
['Shea O\'Sullivan', '"Graphic design is exciting to me because it is a powerful tool that can legitimize ideas and display information in clear and meaningful ways. I love design because it occupies a corner of business that runs on hopefulness about the future of someone\'s idea, work, or creation, and it feels special to empower people in that way. Design pursuits are always engaging because they require careful consideration of learned visual histories, technical reasoning and layers of creative experimentation; adding and subtracting. The process is the best part. 
"'],
['Tanya Hosseiny', 'philosophy'],
['Tarrea Tolbert', 'philosophy'],
['Taylor Bosch', 'philosophy'],
['Thomas Kim', 'philosophy'],
['Timothy Green', 'philosophy'],
['Tjark Riddle', 'philosophy'],
['Tony Li', 'He wants to add more time - ask professor'],
['Travis Marr', 'philosophy'],
['Tyler Browne', 'philosophy'],
['Victoria Dai', 'philosophy'],
['Vincent Lim', 'philosophy'],
['Vy Nguyen', 'philosophy'],
['Wei Wei Lin', 'philosophy'],
['Wen Liang', 'philosophy'],
['Wilson Lee', 'philosophy'],
['Winnie Manyin Guan', 'philosophy'],
['Winta Semere', 'philosophy'],
['Yancy Martinez', 'philosophy'],
['Yumiko Inoue', 'philosophy'],
['Zhihui Zhang', 'philosophy'],
]
