/*
	THIS IS THE FILE FOR PROJECT 2 DETAILS
*/

var designatedStudent = parseInt(localStorage.getItem('designatedStudent'));

var studentProject2Details = [
['Aaron Urban', 'title', 'img1', 'img2', 'img3', 'description'],
['Alejandra Romero', 'DESO', 'images/Alejandra_Romero/Alejandra_Romero_SecondProject1.jpg', 'images/Alejandra_Romero/Alejandra_Romero_SecondProject2.jpg', 'images/Alejandra_Romero/Alejandra_Romero_SecondProject3.jpg', 'This project was a collaboration with a former 300 classmate, Alexis Joseph. Our purpose was to create a eco friendly shoe, allowing biomimicry to influenced the principles of use, look, and resources. Our shoe would be made of, Desserto a strong, breathable material that can last at least ten years. Desserto\'s cactus leather is organic, biodegradable, and soft. We created DESO, a unisex sneaker that can accommodate any style and comfort. DESO is both aesthetically pleasing and a great use to their everyday life. We made sure that our shoe made users feel confident and empowered by colors that represent strength and divinity.'],
['Alex Bang', 'title', 'img1', 'img2', 'img3', 'description'],
['Alex Inokuchi-Garvin', 'title', 'img1', 'img2', 'img3', 'description'],
['Alexis Joseph', 'UBUN2 Magazine', 'images/Alexis_Joseph/Alexis_Joseph_SecondProject1.jpg', 'images/Alexis_Joseph/Alexis_Joseph_SecondProject2.jpg', 'images/Alexis_Joseph/Alexis_Joseph_SecondProject3.jpg', 'UBUN2 is an arts and culture community based magazine and media outlet, that illuminates Africana Diaspora through investigative features on the cultural and artistic trends in the Americas. We offer in-depth interviews of contemporary creators in our community and a window into the world of artists who are re-envisioning what it means to be Africana. Ubuntu means “a quality that includes the essential human virtues; compassion and humanity.” Ubuntu focuses on unifying the community and shedding light to artist that depict Africana is a dynamic art form relating to cultures around the Americas. https://issuu.com/alexisjoseph17/docs/ubun2indesignnn'],
['Alexis De la Torre', 'title', 'img1', 'img2', 'img3', 'description'],
['Alyssa Cortez', 'Arizona Sweet Tea Can Redesign', 'Alyssa_Cortez_SecondProject1.jpg', 'Alyssa_Cortez_SecondProject2.jpg', 'Alyssa_Cortez_SecondProject3.jpg', 'I was asked to choose a brand and flavor of sweet tea and redesign the whole can without using the brand name. I chose the fonts and created a new color palette using two colors of my choice. This was my first project that allowed me to explore package design and I was very happy with the outcome.'],
['Ameer Razman Chin', 'Concrete Typographic Book Cover', 'images/Ameer_RazmanChin/Ameer_RazmanChin_SecondProject1.JPG', 'images/Ameer_RazmanChin/Ameer_RazmanChin_SecondProject2.JPG', 'images/Ameer_RazmanChin/Ameer_RazmanChin_SecondProject3.jpg', 'In this project, I was asked to experiment in creating physical type using any material that seems to fit the book cover we are redesigning. I chose to redesign one of Stephen King\'s book, Desperation, and recreate the title using dried moss to simulate some sort of growth happening from within the body. I photographed the type on textured glass with colored lighting to emulate blood and veins inside the body. '],
['Amy Lau', 'U-CAN-LELE', 'images/Amy_Lau/amy_lau_secondproject1.jpg', 'images/Amy_Lau/amy_lau_secondproject2.jpg', 'images/Amy_Lau/amy_lau_secondproject3.jpg', 'Project from DES 460 (Rapid Prototyping) : The goal of this project was to create a flat pack hand tool using Fusion360 and laser cutting. I created the U-CAN-LELE, a DIY ukulele for adults and children alike. It’s easy to assemble with simple instructions. In addition to bringing fun and entertainment, this musical instrument can be used a learning tool for kids to improve their hand eye coordination skills.'],
['Angela Feng', 'title', 'img1', 'img2', 'img3', 'description'],
['Angela Gabriel', 'title', 'img1', 'img2', 'img3', 'description'],
['Ashley O\'Brien', 'title', 'img1', 'img2', 'img3', 'description'],
['Brett McCormack', 'Sana Fulgorque', 's f g 1.png', 's f g dod.png', 'IMG_7791.JPG', 'A guitar which utilizes electroluminescent film to create a visual stimulus which responds to the music coming out of the guitar.'],
['Brian Liu', 'title', 'img1', 'img2', 'img3', 'description'],
['Briana Gardener', 'Article Redesign ', 'Briana_Gardener-SecondProject1.jpg', 'Briana_Gardener-SecondProject2.jpg', 'Briana_Gardener-SecondProject3.jpg', '"Taking an article addressing issues in modern-day graphic design, designers were challenged to redesign the article layout to further engage the audience. Inspired by old-school Cornell notes, this redesign was created with the main goal of supporting the digestion of information throughout the article, while maintaining an engaging aesthetic. "'],
['Calvin Smith', 'title', 'img1', 'img2', 'img3', 'description'],
['Carlos Rosas Lopez', 'Dewalt Workshop Mouse Project', 'Juan_Rosas_SecondProject1.jpeg', 'Juan_Rosas_SecondProject2.jpeg', 'Juan_Rosas_SecondProject3.jpeg', 'Create an ergonomic computer workshop mouse that incorporates both a hard outer shell and soft rubber over-mold features. The mouse designed for workshop computers operating CNC machines. Design is inspired by the design language of the DeWALT company.'],
['Casey Goldman', 'title', 'img1', 'img2', 'img3', 'description'],
['Charlie Pham', 'title', 'img1', 'img2', 'img3', 'description'],
['Chayla King', 'title', 'img1', 'img2', 'img3', 'description'],
['Chengming Zhang', 'title', 'img1', 'img2', 'img3', 'description'],
['Chi ki Foo', 'title', 'img1', 'img2', 'img3', 'description'],
['Chongzhou Wang', 'title', 'img1', 'img2', 'img3', 'description'],
['Chris Bateman', 'title', 'img1', 'img2', 'img3', 'description'],
['Christian Reyes', 'title', 'img1', 'img2', 'img3', 'description'],
['Christopher Nguyen', 'title', 'img1', 'img2', 'img3', 'description'],
['Christopher Gonzalez', 'title', 'img1', 'img2', 'img3', 'description'],
['Cindy Lopez', 'title', 'img1', 'img2', 'img3', 'description'],
['Connie Mach', 'title', 'img1', 'img2', 'img3', 'description'],
['Connor Dohmen', 'title', 'img1', 'img2', 'img3', 'description'],
['Cory Vaile', 'Monster Movie Poster', 'Cory_Vaile_SecondProject1.jpg', 'Cory_Vaile_SecondProject2.png', 'Cory_Vaile_SecondProject3.jpg', 'This project was completed as part of DES 325 Graphic Design 1. The first part of the project to photograph an existing figure or toy using Adobe Capture and recreate the figure as a vector in Illustrator. The final part was to incorporate lettering into the composition utilizing different shapes within the figure. '],
['Crisanto Dela Pena', 'title', 'img1', 'img2', 'img3', 'description'],
['Crystal Candalla', 'title', 'img1', 'img2', 'img3', 'description'],
['Dakota Clark', 'title', 'img1', 'img2', 'img3', 'description'],
['Daniel Genis', 'title', 'img1', 'img2', 'img3', 'description'],
['Daniel Chu', 'title', 'img1', 'img2', 'img3', 'description'],
['Daniela Cabezas', 'Sugar Rush', 'images/Daniela_Cabezas/daniela_cabezas_secondproject1.jpg', 'images/Daniela_Cabezas/daniela_cabezas_secondproject2.jpg', 'images/Daniela_Cabezas/daniela_cabezas_secondproject3.jpg', 'Sugar Rush was a project in which I was assigned to create a travel booklet with locations of my choosing. Sugar Rush revolves around showing the reader sweet places in the city from pastry shops to boba places. '],
['Daniela Alcaraz', 'title', 'img1', 'img2', 'img3', 'description'],
['David Matthew Sanchez', 'Cujo Cover Redesign ', 'images/David_Sanchez/David_Sanchez_SecondProject1.png', 'images/David_Sanchez/David_Sanchez_SecondProject2.png', 'images/David_Sanchez/David_Sanchez_SecondProject3.png', 'Select one book from a current or recent New York Times hardcover bestseller list that has a short title (approx 1–4 words). Redesign this cover, typographically, using physical effects on one or more words of the title, to express the mood, concept, and/or theme of the book. '],
['Dean Cohen', 'title', 'img1', 'img2', 'img3', 'description'],
['Delmy Cordon', 'title', 'img1', 'img2', 'img3', 'description'],
['Devan Ponce', 'MuniAlert', 'Devan_Ponce_MuniAlert1.jpg', 'Devan_Ponce_MuniAlert2.jpg', 'Devan_Ponce_MuniAlert3.jpg', '"MuniAlert is a communication light fixture, improving the safety of riders and increasing bus drivers efficiency . MuniAlert references the iconic Muni Worm Logo, serving as a Way-finding element. MuniAlert is a QuickBuild solution. It can be easily installed, moved and adjusted."'],
['Dezza Vidrio', 'title', 'img1', 'img2', 'img3', 'description'],
['Dominika Laukova', 'title', 'img1', 'img2', 'img3', 'description'],
['Edilson Diaz', 'Yeezy Boost Shoe Product Line - Water Bottle ', 'Edilson_Diaz_SecondProject1.png', 'Edilson_Diaz_SecondProject2.png', 'Edilson_Diaz_SecondProject3.jpg', 'For this project we were required to make a product line of something that we were interested in. I chose shoes because I\'m passionate about shoes. The Yeezy Boost shoes by Rap artist Kanye West caught my attention, so I decided to base my water bottle after the design of the Yeezy Boost shoe. It was a challenging design but I managed to get it done. '],
['Edward Bond', 'title', 'img1', 'img2', 'img3', 'description'],
['Elaina Keegan', 'title', 'img1', 'img2', 'img3', 'description'],
['Esther Chin', 'title', 'img1', 'img2', 'img3', 'description'],
['Fernando Maldonado', 'title', 'img1', 'img2', 'img3', 'description'],
['Francisco Tapia', 'title', 'img1', 'img2', 'img3', 'description'],
['Gabriela Pasquini', 'title', 'img1', 'img2', 'img3', 'description'],
['Gabrielle Kop', 'title', 'img1', 'img2', 'img3', 'description'],
['Hayden Wolf', 'title', 'img1', 'img2', 'img3', 'description'],
['Iversander Marroquin', 'title', 'img1', 'img2', 'img3', 'description'],
['Jack Tenley', 'title', 'img1', 'img2', 'img3', 'description'],
['Jake Smit', 'title', 'img1', 'img2', 'img3', 'description'],
['Jason Appler', 'title', 'img1', 'img2', 'img3', 'description'],
['Jasper Salomon', 'title', 'img1', 'img2', 'img3', 'description'],
['Jaynie Angelique Batin', 'title', 'img1', 'img2', 'img3', 'description'],
['Jenna M. Stamm', 'Bad Blood / Concrete Typographic Book Cover', 'images/Jennifer_Stamm/Jennifer_Stamm_BadBlood.jpg', 'images/Jennifer_Stamm/Jennifer_Stamm_BadBlood2.jpg', '', 'For this project we were asked to conceptually integrate concrete typography with layout and photography. After selecting a book from the New York Times bestseller list [with an underwhelming cover design], we were tasked to redesign said cover by physically and photographically manipulating a background image and part of the title\'s text to convey the book\'s theme, eventually incorporating additional typesetting. I chose ""Bad Blood"" as my cover redesign, the nonfiction page-turner about the Theranos tech start-up blood testing scandal.'],
['Jesse Vo', 'title', 'img1', 'img2', 'img3', 'description'],
['Jessica Noriega', 'title', 'img1', 'img2', 'img3', 'description'],
['Jesus Calderon', 'title', 'img1', 'img2', 'img3', 'description'],
['Jesus Negrete', 'title', 'img1', 'img2', 'img3', 'description'],
['Johnathon Tott-Berger', 'Beer Me! It\'s 4:59', 'Johnathon_Tott-Berger_SecondProject1.jpg', 'Johnathon_Tott-Berger_SecondProject2.jpg', 'Johnathon_Tott-Berger_SecondProject3.jpg', 'The intent for this beer can design is for the user to engage with the can in ways other than the can\'s normal function. This was achieved by breaking apart the name by words, setting each word below one-another and offsetting them so that the last two words can only be finished reading by user insight or by turning the can. One challenge for this design was incorporating a nutrition label on the can which most beer cans don\'t typically have. This goal was accomplished through researching the active ingredients and how they are tied together which was then translated into the overlapping bubble shaped circles. '],
['Jonathan Ogata', 'title', 'img1', 'img2', 'img3', 'description'],
['Jonathan Camacho', 'Nimbu Cloud Lamp', 'NImbuPoster.jpg', 'NimbuMokcup.jpg', 'img3', 'For my creative process course, we were given the assignment to create a lamp made from upcycled materials. I approached this project by wanting to create an ambient light using materials like polyester fiber, paper lanterns, hot glue sticks, and LED lights. The Nimbu Cloud brings an overall uplift to any room it is placed in. The versatility of this ambient light makes it a fun addition to a party or a perfect place for a nursery that can help your child fall asleep at ease.'],
['Jonny Ogata', 'title', 'img1', 'img2', 'img3', 'description'],
['Juliana Cacciaroni', 'title', 'img1', 'img2', 'img3', 'description'],
['Karina Zalac', 'Davis Creamery Website', 'images/Karina_Zalac/Karina_Zalac_SecondProject1.jpg', 'images/Karina_Zalac/Karina_Zalac_SecondProject2.jpg', 'images/Karina_Zalac/Karina_Zalac_SecondProject3.jpg', 'For my DES 427: Interactive Design final, I chose to design a website for a business that I used to work at called DavisCreamery. They are a local ice cream shop in my hometown. I decided to make them a website prototype on Figma because their previous one was pretty outdated and I know the business well. I aimed to design a modern, simple, easy to use the website for their business.'],
['Katherine Berg', 'title', 'img1', 'img2', 'img3', 'description'],
['Kenny Ngo', 'DES 425 — Magazine Design', 'Kenny_Ngo_SecondProject.png', 'Kenny_Ngo_SecondProject2.png', 'Kenny_Ngo_SecondProject3.png', 'While I\'m not particularly a keen fan of magazine designs, this one professor has made me absolutely love it. I\'ve definitely set myself up not for success when I chose a difficult topic to cover: \"breast implants\". Not only did I choose this article, but I had to take the pictures and generate a format similar to The Cosmopolitan magazine. With the proper guidance, I loved the results.'],
['Kevin Lambert', 'Smartwatch Dock', 'images/Kevin_Lambert/Kevin_Lambert_SecondProject1.jpg', 'images/Kevin_Lambert/Kevin_Lambert_SecondProject2.jpg', 'images/Kevin_Lambert/Kevin_Lambert_SecondProject3.jpg', 'This laser cutting project was an opportunity to become familiar with some of the machinery available on campus. Novelty docks already exist for charging Apple watches, but none of them emulate a mid-century TV set. The idea here was to hide the excess cabling and watchstrap within the television cabinet. My final vision for this project would be a full kit for DIY assembly.'],
['Khang Hoang', 'title', 'img1', 'img2', 'img3', 'description'],
['Korina Moreno', 'title', 'img1', 'img2', 'img3', 'description'],
['Kristy Chi', 'title', 'img1', 'img2', 'img3', 'description'],
['Kwanwu Yu', 'title', 'img1', 'img2', 'img3', 'description'],
['Kyle Millhollin', 'title', 'img1', 'img2', 'img3', 'description'],
['Lauren Pattugalan', 'title', 'img1', 'img2', 'img3', 'description'],
['Lauren Hohls', 'title', 'img1', 'img2', 'img3', 'description'],
['Leilani Paz', 'title', 'img1', 'img2', 'img3', 'description'],
['Lemuel Manalo', 'title', 'img1', 'img2', 'img3', 'description'],
['Linda Lueng', 'title', 'img1', 'img2', 'img3', 'description'],
['Lois Chen', 'title', 'img1', 'img2', 'img3', 'description'],
['Madison Macha', 'title', 'img1', 'img2', 'img3', 'description'],
['Mahya Lewis', 'title', 'img1', 'img2', 'img3', 'description'],
['Mariana De Araujo Souto', 'title', 'img1', 'img2', 'img3', 'description'],
['Mariantonia Cambareri', 'Diwine Packaging', 'images/Mariantonia_Cambareri/Mariantonia_Cambareri_SecondProject1.jpg', 'images/Mariantonia_Cambareri/Mariantonia_Cambareri_SecondProject2.jpg', 'images/Mariantonia_Cambareri/Mariantonia_Cambareri_SecondProject3.jpg', 'Diwine is a Pinot Grigio Rosé product of California. The intention was to create a project that emphasizes the wine and the material aspect of wine production—the artisanal work in creating wines. The target market is not gender-specific therefore the product takes distance from gender stereotypes. We’ve all heard the clichéd thinking that women like lighter, sweeter wines while men prefer big, bold and prestigious wine. But research (and common sense) says otherwise. By using a photo to create the logo is unexpected, while the content of the photo—the letterpress—nods at the historical aspect of the wine-making tradition. This approach comes from the desire to create a strong mixing of textures—the transparent and colorful universe of the watercolor and the exploration of the ancient art of Letterpress printing enhancing the qualities of wood and metal typefaces.'],
['Marielle Cabillo', '"A Place for Us" Redesign', 'Marielle_Cabillo_SecondProject1.jpg', 'Marielle_Cabillo_SecondProject2.jpg', 'Marielle_Cabillo_SecondProject3.jpg', 'This is a redesigned cover of Fatima Farheen Mirza\'s book entitled, "A Place for Us." The novel is about love, compassion, cruelty, and differences. Because the novel is centered around the family during a wedding, I captured a photo that resembles the elegance of a veil, with a tear to symbolize the tension between characters. '],
['Mary Motley', 'title', 'img1', 'img2', 'img3', 'description'],
['Mattie Nye', 'title', 'img1', 'img2', 'img3', 'description'],
['Mauricio Morazan Mejia', 'TYPEFACE SPECIMEN BOOKLET: GARAMOND BROCHURE', 'images/Mauricio_Morazan/Mauricio_Morazan_SecondProject1.jpg', 'images/Mauricio_Morazan/Mauricio_Morazan_SecondProject2.jpg', 'images/Mauricio_Morazan/Mauricio_Morazan_SecondProject3.jpg', 'For this Typeface Specimen Booklet, my goal was to showcase the history of the Garamond typeface by showing the ways on how we can use the Garamond font on a contemporary way, so the aspects of this Brochure is about exposing an informational storytelling way on how the Garamond font started by Claude Garamond by showcasing the characterization of the font. Also, I wanted to display some vibrant colors such as blue and yellow so that way to create that swiss design feels which uses two color pallets. my goal was to showcase the Garamond font into a way that the Garamond can still use it has today on designs and contemporary forms of art.'],
['Max Kolden', 'title', 'img1', 'img2', 'img3', 'description'],
['Maxwell Lohr', 'title', 'img1', 'img2', 'img3', 'description'],
['Mia Dong', 'title', 'img1', 'img2', 'img3', 'description'],
['Michael Ihle', "How to Make A.I. That's Good for People", 'mag1.jpg', 'mag3.jpg', 'mag4.jpg', '"This was a magazine redesign for an assigned magazine article. I wanted to focus on the illustrations to help visualize the story being told in the article. By simply looking at the illustrations you can understand the tone taken by the author and they stance on A.I. "'],
['Michelle Nam', 'title', 'img1', 'img2', 'img3', 'description'],
['Monica Chum', 'The Little Mermaid', 'images/Monica_Chum/Monica_Chum_SecondProject1.jpg', 'images/Monica_Chum/Monica_Chum_SecondProject2.jpg', 'images/Monica_Chum/Monica_Chum_SecondProject3.jpg', 'Throughout the story, the little mermaid envelops herself in her desires, so much so that she loses sight of all of the potential consequences. There\'s at least one distinct thing the little mermaid wants in each chapter and at each of those parts, there would be a red, transparent page (if this were an actual printed book). Printed on the transparency is the body copy, the reality of things. But when the reader turns the page, they will see that these key phrases are only repeated within the bounds of the text box to illustrate how her yearnings are limited by the bounds of reality. In the last chapter, the key phrase “I want him to be happy” is only said once on this page to symbolize her letting go of her obsessive desires. Yet, the phrase is still trapped in the confines of the text box.'],
['Natasha Sherbaf', 'title', 'img1', 'img2', 'img3', 'description'],
['Nicolas Noratto', 'title', 'img1', 'img2', 'img3', 'description'],
['Nik Dommen', 'title', 'img1', 'img2', 'img3', 'description'],
['Niklaus Dommen', 'title', 'img1', 'img2', 'img3', 'description'],
['Noah Castro', 'title', 'img1', 'img2', 'img3', 'description'],
['Nora Kettles', 'title', 'img1', 'img2', 'img3', 'description'],
['Omar Hernandez', 'title', 'img1', 'img2', 'img3', 'description'],
['Pablo Wu', 'title', 'img1', 'img2', 'img3', 'description'],
['Pamela Liutama', 'title', 'img1', 'img2', 'img3', 'description'],
['Paramveer Singh', 'title', 'img1', 'img2', 'img3', 'description'],
['Rachel Ward', 'title', 'img1', 'img2', 'img3', 'description'],
['Regine Ong', 'title', 'img1', 'img2', 'img3', 'description'],
['Rexford Adams', 'title', 'img1', 'img2', 'img3', 'description'],
['Roberto Berrocal-Pujol', 'Mancala Stool', 'Roberto_Berrocal-Pujol_Mancala Stool (JPG)1.jpg', 'Roberto_Berrocal-Pujol_Mancala Stool (JPG)2.jpg', 'Roberto_Berrocal-Pujol_Mancala Stool (JPG)3.jpg', 'The word "mancala" comes from the Arabic word naqala, which means “to move”. The repition of lines innately invoke the feeling of movement. The mancala stool was designed with influences from the repition of vertical lines seen throughout nature. Observed in natural formations like rock sedimintation, canyons, bone structures, but also seen in man made formations such as skylines.'],
['Ryan Bach', 'title', 'img1', 'img2', 'img3', 'description'],
['Ryan Spalding', 'title', 'img1', 'img2', 'img3', 'description'],
['Sabrina Umbay', 'title', 'img1', 'img2', 'img3', 'description'],
['Samuel Vasquez', 'title', 'img1', 'img2', 'img3', 'description'],
['Sarina Campanella', 'Therapy Fashion Website (HTML/CSS) UX/UI Design', 'Therapy_show.png', 'Therapy_show.png', 'img3', '"Therapy is a collaborative project that was assigned to give the existing San Francisco retailer a fresh, new UX/UI friendly image with compelling features that would appeal to a millennial crowd. Kitty Su and I engaged in a personal interview to create a detailed design brief, which was then converted into a HTML/CSS coded website using Github. The result was satisfaction and success for parties on both ends to bring an updated look to the brand. 
"'],
['Sean Huang', 'Pelliconi Bottle Cap Challange: Grupull Cap', 'Sean Huang_First Project1.jpg.jpg', 'Sean Huang _SecondProject2.jpg.jpg', 'Sean Huang _SecondProject3.jpg.png', 'A bottle cap that is designed to enhance human interaction, providing the options of  both users to work together to open up the beverage, or simply pry it off with hands.'],
['Shaine Edmond', 'title', 'img1', 'img2', 'img3', 'description'],
['Shea O\'Sullivan', 'It Is Hard Sometimes ', 'Shea_Osullivan_SecondProject1.jpg', 'Shea_Osullivan_SecondProject2.jpg', 'Shea_Osullivan_SecondProject3.jpg', 'For this book cover assignment I chose the photographer and artist Olaf Breuning. This book is meant to be a large coffee table style book of Breuning\'s photography. The title \"It Is Hard Sometimes\" is a reference to one of his art pieces.'],
['Tanya Hosseiny', 'title', 'img1', 'img2', 'img3', 'description'],
['Tarrea Tolbert', 'title', 'img1', 'img2', 'img3', 'description'],
['Taylor Bosch', 'title', 'img1', 'img2', 'img3', 'description'],
['Thomas Kim', 'title', 'img1', 'img2', 'img3', 'description'],
['Timothy Green', 'title', 'img1', 'img2', 'img3', 'description'],
['Tjark Riddle', 'title', 'img1', 'img2', 'img3', 'description'],
['Tony Li', 'Paper Airplane', 'images/Tony_Li/Tony_Li_SecondProject01.jpg', 'images/Tony_Li/Tony_Li_Tony_Li_SecondProject02.jpg', 'images/Tony_Li/Tony_Li_SecondProject03.jpg', 'This project is a UI version that I design a 2D game called "Paper Airplane" And the project include the concept of the 2D game.'],
['Travis Marr', 'title', 'img1', 'img2', 'img3', 'description'],
['Tyler Browne', 'title', 'img1', 'img2', 'img3', 'description'],
['Victoria Dai', 'title', 'img1', 'img2', 'img3', 'description'],
['Vincent Lim', 'title', 'img1', 'img2', 'img3', 'description'],
['Vy Nguyen', 'title', 'img1', 'img2', 'img3', 'description'],
['Wei Wei Lin', 'title', 'img1', 'img2', 'img3', 'description'],
['Wen Liang', 'title', 'img1', 'img2', 'img3', 'description'],
['Wilson Lee', 'title', 'img1', 'img2', 'img3', 'description'],
['Winnie Manyin Guan', 'title', 'img1', 'img2', 'img3', 'description'],
['Winta Semere', 'title', 'img1', 'img2', 'img3', 'description'],
['Yancy Martinez', 'title', 'img1', 'img2', 'img3', 'description'],
['Yumiko Inoue', 'title', 'img1', 'img2', 'img3', 'description'],
['Zhihui Zhang', 'title', 'img1', 'img2', 'img3', 'description'],
]

function getStudentProj2Title() {
    return studentProject2Details[designatedStudent][1];
}

function getStudentProj2Images() {
    text = '<img class="myImg" src="' + studentProject2Details[designatedStudent][2] + '">';
    text += '<img class="myImg" src="' + studentProject2Details[designatedStudent][3] + '">';
    if (studentProject2Details[designatedStudent][4] !== '') {
    	text += '<img class="myImg" src="' + studentProject2Details[designatedStudent][4] + '">';
    }
    return text;
}

function getStudentProj2Description() {
    return studentProject2Details[designatedStudent][5];
}