/*
	THIS IS THE FILE FOR PROJECT 1 DETAILS
*/

var designatedStudent = parseInt(localStorage.getItem('designatedStudent'));

var studentProject1Details = [
['Aaron Urban', 'title', 'img1', 'img2', 'img3', 'description'],
['Alejandra Romero', 'Lana Del Rey– Vinyl Set', 'images/Alejandra_Romero/Alejandra_Romero_FirstProject1.jpg', 'images/Alejandra_Romero/Alejandra_Romero_FirstProject2.jpg', 'images/Alejandra_Romero/Alejandra_Romero_FirstProject3.jpg', 'This is a design for a series of three album artworks for the musical artist Lana Del Rey. The project utilizes variable elements as well as consistent type hierarchy in order to create a unified stylistic set. The interaction of type and image was a key criteria for this project. Stylistically, the artist is known for her vintage aesthetic and nostalgia. I wanted to incorporate polaroids within the set for a unified vintage feel. For the final iteration, I simplified my idea to focus on using a single rose throughout the set. For the track Young and Beautiful, I chose a delicate rose to represent a beautiful symphony. For the track Black Beauty, I went with a dark red rose stained with blood to represent the lyrics. The track Lust for Life is expressed through a withered rose to represent the idea of death in the lyrics.'],
['Alex Bang', 'title', 'img1', 'img2', 'img3', 'description'],
['Alex Inokuchi-Garvin', 'title', 'img1', 'img2', 'img3', 'description'],
['Alexis Joseph', 'Shape of Sound Poster and Animation', 'images/Alexis_Joseph/Alexis_Joseph_FirstProject1.jpg', 'images/Alexis_Joseph/Alexis_Joseph_FirstProject2.jpg', 'images/Alexis_Joseph/Alexis_Joseph_FirstProject3.jpg', 'I designed a 12 x 12 cover for the song Atari by Hiatus Kaiyote using a basic shape, line and dot based visual language. I also created a 8 second animation for a clip from the song using Photoshop Timeline.'],
['Alexis De la Torre', 'title', 'img1', 'img2', 'img3', 'description'],
['Alyssa Cortez', 'Endometriosis Awareness (DES 525)', 'Alyssa_Cortez_FirstProject1.jpg', 'Alyssa_Cortez_FirstProject2.jpg', 'Alyssa_Cortez_FirstProject3.jpg', 'The goal was to execute a self-guided project using only an egg as your muse to help you figure out what the topic and final outcome would be. The topic I chose was the common yet not commonly known female disease of endometriosis, with my final outcome being an informational zine and poster. The poster would ideally be in doctor’s offices and clinics as a call to action for women to see their doctors if they think they have endometriosis, as it can cause infertility. The zines provide more information on the disease such as possible treatments and symptoms.'],
['Ameer Razman Chin', 'BORDERS: Article Redesign ', 'images/Ameer_RazmanChin/Ameer_RazmanChin_FirstProject1.jpg', 'images/Ameer_RazmanChin/Ameer_RazmanChin_FirstProject2.jpg', 'images/Ameer_RazmanChin/Ameer_RazmanChin_FirstProject3.jpg', 'For this project I was required to find an article related to "borders" and design it to fit in an existing magazine. I have chosen an article written by Eliza Griswold about the Pashtun women using landays which are forms of short-verse poems, to talk about their sufferings in the border of Afghanistan and Pakistan. I chose to design this article to fit in a women focused magazine, Womankind.'],
['Amy Lau', 'Adidas EQT Water Bottle', 'images/Amy_Lau/amy_lau_firstproject1.jpg', 'images/Amy_Lau/amy_lau_firstproject2.jpg', 'images/Amy_Lau/amy_lau_firstproject3.jpg', 'Project from DES 460 (Rapid Prototyping) : The goal of this project was to create a flat pack hand tool using Fusion360 and laser cutting. I created the U-CAN-LELE, a DIY ukulele for adults and children alike. It’s easy to assemble with simple instructions. In addition to bringing fun and entertainment, this musical instrument can be used a learning tool for kids to improve their hand eye coordination skills.'],
['Angela Feng', 'title', 'img1', 'img2', 'img3', 'description'],
['Angela Gabriel', 'title', 'img1', 'img2', 'img3', 'description'],
['Ashley O\'Brien', 'title', 'img1', 'img2', 'img3', 'description'],
['Brett McCormack', 'Kottosynthetto', 'kotto 4 6.png', 'kotto 4 6 dos.png', 'kotto 46 tres.png', 'A portable musical instrument which allows the user to compose and compile tracks, also allows the user to play two instruments simultaneously without hitting a single note out of key. As long as the user can keep rhythm they can use this device to make songs regardless of their prior music theory knowledge.'],
['Brian Liu', 'title', 'img1', 'img2', 'img3', 'description'],
['Briana Gardener', 'Type Hierarchy', 'Briana_Gardener_FirstProject1.jpg', 'Briana_Gardener_FirstProject2.jpg', 'Briana_Gardener_FirstProject3.jpg', 'After finding an article that captured their attention, designers were given 27 different words, such as “balance, texture, and compression.” They were then challenged to use the type from the headline and content of the article to convey these words. '],
['Calvin Smith', 'title', 'img1', 'img2', 'img3', 'description'],
['Carlos Rosas Lopez', 'title', 'img1', 'img2', 'img3', 'description'],
['Casey Goldman', 'title', 'img1', 'img2', 'img3', 'description'],
['Charlie Pham', 'title', 'img1', 'img2', 'img3', 'description'],
['Chayla King', 'title', 'img1', 'img2', 'img3', 'description'],
['Chengming Zhang', 'title', 'img1', 'img2', 'img3', 'description'],
['Chi ki Foo', 'title', 'img1', 'img2', 'img3', 'description'],
['Chongzhou Wang', 'title', 'img1', 'img2', 'img3', 'description'],
['Chris Bateman', 'title', 'img1', 'img2', 'img3', 'description'],
['Christian Reyes', 'title', 'img1', 'img2', 'img3', 'description'],
['Christopher Nguyen', 'title', 'img1', 'img2', 'img3', 'description'],
['Christopher Gonzalez', 'title', 'img1', 'img2', 'img3', 'description'],
['Cindy Lopez', 'title', 'img1', 'img2', 'img3', 'description'],
['Connie Mach', 'title', 'img1', 'img2', 'img3', 'description'],
['Connor Dohmen', 'title', 'img1', 'img2', 'img3', 'description'],
['Cory Vaile', 'Package Design for the Do Nothing Toy', 'Cory_Vaile_FirstProject1.jpeg', 'Cory_Vaile_FirstProject2.jpeg', 'Cory_Vaile_FirstProject3.jpg', 'This was a package design project completed as part of DES 300. The goal was to design a brand and packaging for a wooden toy puzzle. During this project I researched the history of different toy packaging and created a physical mockup with my own layout and illustrations. '],
['Crisanto Dela Pena', 'title', 'img1', 'img2', 'img3', 'description'],
['Crystal Candalla', 'title', 'img1', 'img2', 'img3', 'description'],
['Dakota Clark', 'title', 'img1', 'img2', 'img3', 'description'],
['Daniel Genis', 'title', 'img1', 'img2', 'img3', 'description'],
['Daniel Chu', 'title', 'img1', 'img2', 'img3', 'description'],
['Daniela Cabezas', 'Frankenstein or The Modern Prometheus', 'images/Daniela_Cabezas/daniela_cabezas_firstproject1.jpg', 'images/Daniela_Cabezas/daniela_cabezas_firstproject2.jpg', 'images/Daniela_Cabezas/daniela_cabezas_firstproject3.jpg', 'One of the main goals of the project was to make the text of the book as legible as possible for the reader. We had the assignment to customize the book\'s typography and create the artwork for the cover and the artwork in the book.'],
['Daniela Alcaraz', 'title', 'img1', 'img2', 'img3', 'description'],
['David Matthew Sanchez', 'The Metamorphosis Book Design', 'images/David_Sanchez/David_Sanchez_FirstProject1.png', 'images/David_Sanchez/David_Sanchez_FirstProject3.png', 'images/David_Sanchez/David_Sanchez_FirstProject3.png', 'This project was to read and design the cover, layout, and visuals for the book The Metamorphosis. This project had specific guidelines but had creative freedom on how to reinterpret and visually design the book. '],
['Dean Cohen', 'title', 'img1', 'img2', 'img3', 'description'],
['Delmy Cordon', 'title', 'img1', 'img2', 'img3', 'description'],
['Devan Ponce', 'L-360', 'Devan_Ponce_L360_1-02.jpg', 'Devan_Ponce_L360_2-03.jpg', 'Devan_Ponce_L360_3-04.jpg', '"Re-thinking the Lantern. Given a camping environment, L-360 offers users adaptability including hanging, walking and resting. L-360 has a minimalist look for easy and intuitive in use. Components are hidden for a sleek look and durability."'],
['Dezza Vidrio', 'title', 'img1', 'img2', 'img3', 'description'],
['Dominika Laukova', 'title', 'img1', 'img2', 'img3', 'description'],
['Edilson Diaz', 'Older Dinosaur Trophy ', 'Edilson_Diaz_FirstProject1.jpg', 'Edilson_Diaz_FirstProject2.jpg', 'Edilson_Diaz_FirstProject3.jpg', 'This is one of my favorite projects that I got to make in Model Development DES 310 because not only did I have the freedom to go in whichever direction I wanted, but I also got to implement all the skills that I had learned in this class on this final piece of work. My assigned trophy was to make design and produce "The Oldest Dinosaur" trophy. I used a combination of Renshape, Pink Styrofoam and 3D printed parts for my model. We were also required to make a certificate to go along the trophy. I had a lot of fun completing this project. '],
['Edward Bond', 'title', 'img1', 'img2', 'img3', 'description'],
['Elaina Keegan', 'title', 'img1', 'img2', 'img3', 'description'],
['Esther Chin', 'title', 'img1', 'img2', 'img3', 'description'],
['Fernando Maldonado', 'title', 'img1', 'img2', 'img3', 'description'],
['Francisco Tapia', 'title', 'img1', 'img2', 'img3', 'description'],
['Gabriela Pasquini', 'title', 'img1', 'img2', 'img3', 'description'],
['Gabrielle Kop', 'title', 'img1', 'img2', 'img3', 'description'],
['Hayden Wolf', 'title', 'img1', 'img2', 'img3', 'description'],
['Iversander Marroquin', 'title', 'img1', 'img2', 'img3', 'description'],
['Jack Tenley', 'title', 'img1', 'img2', 'img3', 'description'],
['Jake Smit', 'title', 'img1', 'img2', 'img3', 'description'],
['Jason Appler', 'title', 'img1', 'img2', 'img3', 'description'],
['Jasper Salomon', 'title', 'img1', 'img2', 'img3', 'description'],
['Jaynie Angelique Batin', 'title', 'img1', 'img2', 'img3', 'description'],
['Jenna M. Stamm', 'Flat Earther Borders / Magazine Layout ', 'images/Jennifer_Stamm/Jennifer_Stamm_Borders1.jpg', 'images/Jennifer_Stamm/Jennifer_Stamm_Borders2.jpg', '', 'In this assignment, we were asked to analyze and utilize the style sheet for an existing publication, whose aesthetic we wanted to emulate for an existing long-form article on the subject of our interpretation of the word "borders". Using the style of the aforementioned existing publication, we had to produce and incorporate our own original images into the layout. I decided to focus on Flat-Earthers, as they are seen as the fringe of society, almost ""bordering"" its edges. I chose the quarterly magazine, GAGOSIAN, as my editorial layout inspiration.'],
['Jesse Vo', 'title', 'img1', 'img2', 'img3', 'description'],
['Jessica Noriega', 'title', 'img1', 'img2', 'img3', 'description'],
['Jesus Calderon', 'title', 'img1', 'img2', 'img3', 'description'],
['Jesus Negrete', 'title', 'img1', 'img2', 'img3', 'description'],
['Johnathon Tott-Berger', 'Sit–N–Stand Guitar Stand and Stool', 'Tott-Berger_J_DES_460_FinalPresentation _Page_1.jpg', 'Tott-Berger_J_DES_460_FinalPresentation _Page_2.jpg', 'Tott-Berger_J_DES_460_FinalPresentation _Page_3.jpg', 'The intent for this design was to create a stool that had a second purpose when not being sat upon. The aesthetic for this design is Rockabilly and is achieved by using a combination of light and dark stains, a two–toned seat, and golden accents. By staining the wood rather than painting it the stool takes on a rustic country vibe while the golden bass clef notes play to the rhythm and blues of rockabilly music and style. The stool can fit a small amplifier underneath and reduces the overall footprint of at least three to four different items by nesting them together in one. '],
['Jonathan Ogata', 'title', 'img1', 'img2', 'img3', 'description'],
['Jonathan Camacho', 'Frankenstein Book Design ', 'BookDesignMockup1.jpg', 'BookDesignMockup2.jpg', 'img3', '"Throughout Mary Shelley’s Frankenstein, there are many issues tackled varying from insecurities, mystery, and self-loathing. Victor Frankenstein struggles with these feelings of continuous haunting from his past which is why I chose him as a focus for my design. Throughout Mary Shelley’s Frankenstein, there are many issues tackled varying from insecurities, mystery, and self-loathing. Victor Frankenstein struggles with these feelings of continuous haunting from his past which is why I chose him as a focus for my design. The various events in the book are showcased by the different stages of water. Beginning in a solid form of ice that will eventually meltdown to a boiling state envisioning Frankenstein’s inner struggles. "'],
['Jonny Ogata', 'title', 'img1', 'img2', 'img3', 'description'],
['Juliana Cacciaroni', 'title', 'img1', 'img2', 'img3', 'description'],
['Karina Zalac', 'Mapping the Invisible: Making Sense of SF', 'images/Karina_Zalac/Karina_Zalac_FirstProject1.jpg', 'images/Karina_Zalac/Karina_Zalac_FirstProject2.jpg', 'images/Karina_Zalac/Karina_Zalac_FirstProject3.jpg', 'This data visualization poster represents the smells that I encountered during my daily weekday routine. The objective of this project was to test my sense of smell, explore various odors, and visualize their movements from location to location. While my research mainly resulted in negative smells, I surprisingly found good scents amongst the bad ones in the city. I wanted the final poster to have a whimsical look which I achieved through the creation of playful graphics and a free-flowing layout. The goal of this light-hearted poster was to poke fun at the abundance of unpleasant smells that most San Franciscans can expect to encounter while commuting.'],
['Katherine Berg', 'title', 'img1', 'img2', 'img3', 'description'],
['Kenny Ngo', 'DES 425 — Book Cover Design', 'Kenny_Ngo_FirstProject1.jpg', 'Kenny_Ngo_FirstProject2.jpg', 'Kenny_Ngo_FirstProject3.jpg', 'We, as a class, were tasked with creating a book cover for a New York Best Seller book. Through this rigorous process of designing, critiquing, followed by more designing and critiquing, I was able to truly learn what it means to be a designer. There were times when people took critiques personally, but I\'ve learned to be as objective as possible and not fall in love with your work since your proposed solution isn\'t always the best. '],
['Kevin Lambert', 'Prep & Plan', 'images/Kevin_Lambert/Kevin_Lambert_FirstProject1.jpg', 'images/Kevin_Lambert/Kevin_Lambert_FirstProject2.jpg', 'images/Kevin_Lambert/Kevin_Lambert_FirstProject3.jpg', 'Prep -n- Plan is the only storage container on the market that allows the user to track effortlessly date their food for consumption. The target audience includes families seeking to organize their leftovers by freshness and dieters that want to organize their meals. By inverting the flexible dimples on the lid, users can easily indicate any date on their foods, quickly and easily marking either when the food was cooked or the day it is intended to be consumed, all without pens, notes, and excess materials.'],
['Khang Hoang', 'title', 'img1', 'img2', 'img3', 'description'],
['Korina Moreno', 'title', 'img1', 'img2', 'img3', 'description'],
['Kristy Chi', 'title', 'img1', 'img2', 'img3', 'description'],
['Kwanwu Yu', 'title', 'img1', 'img2', 'img3', 'description'],
['Kyle Millhollin', 'title', 'img1', 'img2', 'img3', 'description'],
['Lauren Pattugalan', 'title', 'img1', 'img2', 'img3', 'description'],
['Lauren Hohls', 'title', 'img1', 'img2', 'img3', 'description'],
['Leilani Paz', 'title', 'img1', 'img2', 'img3', 'description'],
['Lemuel Manalo', 'title', 'img1', 'img2', 'img3', 'description'],
['Linda Lueng', 'title', 'img1', 'img2', 'img3', 'description'],
['Lois Chen', 'title', 'img1', 'img2', 'img3', 'description'],
['Madison Macha', 'title', 'img1', 'img2', 'img3', 'description'],
['Mahya Lewis', 'title', 'img1', 'img2', 'img3', 'description'],
['Mariana De Araujo Souto', 'title', 'img1', 'img2', 'img3', 'description'],
['Mariantonia Cambareri', 'Poster Redux_Metamorphosis', 'images/Mariantonia_Cambareri/Mariantonia_Cambareri_FirstProject1.jpg', 'images/Mariantonia_Cambareri/Mariantonia_Cambareri_FirstProject2.jpg', 'images/Mariantonia_Cambareri/Mariantonia_Cambareri_FirstProject3.jpg', 'This poster was realized starting with a three-dimensional object, exploring organic and geometric forms, the relationship between line and solid, as well as other contrasting or harmonious forms. The objective of this exploration was to produce dynamic, simplified visual descriptions of the object integrating it with words and text that communicate an aspect of the object itself. To best express this concept, I was inspired by an epic-mythological poem by Publio Ovidio Nasone, \"Metamorphosis\". Through the narrative voice of Pythagoras, the author exposes the hypothesis of a vision of the world in which the forms assumed by things are not fixed, but changeable: they change continuously, each transforming into another, in a perennial process of metamorphosis.It is in this Pythagorean vision that the problem of death is framed: the body of every man dies, and with it, his identity disappears, but the soul, in itself, does not die, survives precisely through the multiple forms that it will go to taking on through the infinite and incessant process of transmigration and metempsychosis.'],
['Marielle Cabillo', 'title', 'img1', 'img2', 'img3', 'description'],
['Mary Motley', 'title', 'img1', 'img2', 'img3', 'description'],
['Mattie Nye', 'title', 'img1', 'img2', 'img3', 'description'],
['Mauricio Morazan Mejia', 'EMOTIONS OF WEATHER CHANGE - DES 323', 'images/Mauricio_Morazan/Mauricio_Morazan_Antioch_Weather_Mapping1.jpg', 'images/Mauricio_Morazan/Mauricio_Morazan_Antioch_Weather_Mapping2.jpg', 'images/Mauricio_Morazan/Mauricio_Morazan_Antioch_Weather_Mapping3.jpg', 'Weather is the day-to-day state of the atmosphere and pertains to short term changes in conditions of heat, moisture and air movement. Weather results from processes that attempt to equalize the differences in the distribution of net radiant energy from the sun. In other words, the instantaneous state of the atmosphere can be called as the weather. It is usually expressed as fine, fair, foggy, cloudy, rainy, sunny or windy weather. This visualization is a set of data collected by observing the emotions of the people in Antioch CA, the second-largest city in Contra Costa County. The data is based on the weather change from the last four weeks starting from January 29th through February 23rd. My intent for the research is to investigate how our emotions react when there\'s a weather change in the city you resident from, for example, the city I choose to conduct my research is my home place city Antioch CA. the reason is that comparing the city of San Francisco to Antioch, sometimes we have similar weather conditions, San Francisco always has cold and foggy weather, but in Antioch is actually there are moments that the weather changes, for example, in the morning it gets cold, and then almost in the afternoon, it gets warmer, which is typical in Antioch. Also, I found interesting on how people react to the weather, on the data research, I was documenting their emotions by hearing their reaction and get the idea of the people\'s mood.'],
['Max Kolden', 'title', 'img1', 'img2', 'img3', 'description'],
['Maxwell Lohr', 'title', 'img1', 'img2', 'img3', 'description'],
['Mia Dong', 'title', 'img1', 'img2', 'img3', 'description'],
['Michael Ihle', 'Frame Of Life', 'img1', 'img2', 'img3', "The Frame of Life experience shows viewers the beauty of their surroundings that they often missed. People tend to be over stressed, over worked, and overwhelmed with their own life to appreciate what they have around them. This project is to help relief some of life’s stresses by taking a break and “seeing what you miss.” Frames are placed in unique, overlooked, and obscure locations to attract people to stop and appreciate what they commonly walk by. This is an interactive project. Through Instagram, people who see these frames can take pictures and tag/hashtag the page. The page will be updated with the photos that people send in. People are also encouraged to add their own frames by sending pictures of their frame in location to be added to the map."],
['Michelle Nam', 'title', 'img1', 'img2', 'img3', 'description'],
['Monica Chum', 'Hungry Traveler\'s Guide to San Francisco', 'images/Monica_Chum/Monica_Chum_FirstProject1.jpg', 'images/Monica_Chum/Monica_Chum_FirstProject2.jpg', 'images/Monica_Chum/Monica_Chum_FirstProject3.jpg', 'As a tourist, going to a new city or country and trying to find something to eat can be overwhelming. Sometimes, you just want someone to figure out each meal for you. I wanted to design this San Francisco food guide with that idea in mind. It\'s compact, but is packed with information about each food location including ratings, address, popular menu items, fun facts, and illustrations. This project was completed in my first semester as a design student, allowing me to hone my Illustrator skills and develop my love for the program!'],
['Natasha Sherbaf', 'title', 'img1', 'img2', 'img3', 'description'],
['Nicolas Noratto', 'title', 'img1', 'img2', 'img3', 'description'],
['Nik Dommen', 'title', 'img1', 'img2', 'img3', 'description'],
['Niklaus Dommen', 'title', 'img1', 'img2', 'img3', 'description'],
['Noah Castro', 'title', 'img1', 'img2', 'img3', 'description'],
['Nora Kettles', 'title', 'img1', 'img2', 'img3', 'description'],
['Omar Hernandez', 'title', 'img1', 'img2', 'img3', 'description'],
['Pablo Wu', 'title', 'img1', 'img2', 'img3', 'description'],
['Pamela Liutama', 'title', 'img1', 'img2', 'img3', 'description'],
['Paramveer Singh', 'title', 'img1', 'img2', 'img3', 'description'],
['Rachel Ward', 'title', 'img1', 'img2', 'img3', 'description'],
['Regine Ong', 'title', 'img1', 'img2', 'img3', 'description'],
['Rexford Adams', 'title', 'img1', 'img2', 'img3', 'description'],
['Roberto Berrocal-Pujol', 'Rock n\' Roll (Hypotonia Therapy toy)', 'Roberto_Berrocal-Pujol_Rock n\' Roll (Hypotonia Therapy toy)1.jpg', 'Roberto_Berrocal-Pujol_Rock n\' Roll (Hypotonia Therapy toy)2.jpg', 'Roberto_Berrocal-Pujol_Rock n\' Roll (Hypotonia Therapy toy)3.jpg', 'Rock N’ Roll is a game that focuses on gross and fine motor skills, tones the upper body, provides cognitive challenges, and rewards the efforts. Rock N’ Roll is flexible where the child can make their own maze pattern. It is geared for children ages 4- to 6-years-old … but anyone can play!'],
['Ryan Bach', 'title', 'img1', 'img2', 'img3', 'description'],
['Ryan Spalding', 'title', 'img1', 'img2', 'img3', 'description'],
['Sabrina Umbay', 'title', 'img1', 'img2', 'img3', 'description'],
['Samuel Vasquez', 'title', 'img1', 'img2', 'img3', 'description'],
['Sarina Campanella', 'Poppy Drinks', 'Poppy_show.png', 'poppy_show2.png', 'img3', 'Poppy was a brand created to showcase a drink product with similar flavors. This was done by using analogous colors with soft tints. The font itself was created in Adobe Illustrator for a more unique branding image, and mocked-up on cans in Photoshop. '],
['Sean Huang', 'title', 'img1', 'img2', 'img3', 'description'],
['Shaine Edmond', 'title', 'img1', 'img2', 'img3', 'description'],
['Shea O\'Sullivan', 'Venchi Packaging Design ', 'Shea_Osullivan_FristProject1.jpg', 'Shea_Osullivan_FirstProject2.jpeg', 'Shea_Osullivan_First Project3.jpeg', 'Venchi is a classic Italian chocolate brand that sells chocolate Easter eggs and other easter candy in the spring. This packaging is inspired by stained glass windows in Italian cathedrals. The darker color palette is for the dark chocolate eggs and the lighter packaging is for milk chocolate eggs. '],
['Tanya Hosseiny', 'title', 'img1', 'img2', 'img3', 'description'],
['Tarrea Tolbert', 'title', 'img1', 'img2', 'img3', 'description'],
['Taylor Bosch', 'title', 'img1', 'img2', 'img3', 'description'],
['Thomas Kim', 'title', 'img1', 'img2', 'img3', 'description'],
['Timothy Green', 'title', 'img1', 'img2', 'img3', 'description'],
['Tjark Riddle', 'title', 'img1', 'img2', 'img3', 'description'],
['Tony Li', 'Metro to De Young Museum', 'images/Tony_Li/Tony_Li_FirstProject01.jpg', 'images/Tony_Li/Tony_Li_FirstProject03.jpg', 'images/Tony_Li/Tony_Li_FirstProject03.jpg', 'This poster visualizes the feeling of wonder that I had when visiting the De Young Museum. Similar to be a passenger on the Muni and a visitor to the De Young each stop brings something new. In the addition, the artifact can be likened to a checkpoint at each station, and its theme from the area galleries can be likened to the name of each train, and icon expresses what I see and what I feel from the four areas galleries. In addition, its time travel, the train starts from ancient to modern, which are at the right of the map. The feeling of wonder for modern artworks is significantly lower than for ancient artifacts.'],
['Travis Marr', 'title', 'img1', 'img2', 'img3', 'description'],
['Tyler Browne', 'title', 'img1', 'img2', 'img3', 'description'],
['Victoria Dai', 'title', 'img1', 'img2', 'img3', 'description'],
['Vincent Lim', 'title', 'img1', 'img2', 'img3', 'description'],
['Vy Nguyen', 'title', 'img1', 'img2', 'img3', 'description'],
['Wei Wei Lin', 'title', 'img1', 'img2', 'img3', 'description'],
['Wen Liang', 'title', 'img1', 'img2', 'img3', 'description'],
['Wilson Lee', 'title', 'img1', 'img2', 'img3', 'description'],
['Winnie Manyin Guan', 'title', 'img1', 'img2', 'img3', 'description'],
['Winta Semere', 'title', 'img1', 'img2', 'img3', 'description'],
['Yancy Martinez', 'title', 'img1', 'img2', 'img3', 'description'],
['Yumiko Inoue', 'title', 'img1', 'img2', 'img3', 'description'],
['Zhihui Zhang', 'title', 'img1', 'img2', 'img3', 'description'],
]

function getStudentProj1Title() {
    return studentProject1Details[designatedStudent][1];
}

function getStudentProj1Images() {
    text = '<img class="myImg" src="' + studentProject1Details[designatedStudent][2] + '">';
    text += '<img class="myImg" src="' + studentProject1Details[designatedStudent][3] + '">';
    if (studentProject1Details[designatedStudent][4] !== '') {
        text += '<img class="myImg" src="' + studentProject1Details[designatedStudent][4] + '">';
    }
    return text;
}

function getStudentProj1Description() {
    return studentProject1Details[designatedStudent][5];
}
