/*
	THIS IS THE FILE FOR PROJECT 3 DETAILS
*/

var designatedStudent = parseInt(localStorage.getItem('designatedStudent'));

var studentProject3Details = [
['Aaron Urban', 'title', 'img1', 'img2', 'img3', 'description'],
['Alejandra Romero', 'title', 'images/Alejandra_Romero/Alejandra_Romero_CapstoneProject1.jpg', 'images/Alejandra_Romero/Alejandra_Romero_CapstoneProject2.jpg', 'images/Alejandra_Romero/Alejandra_Romero_CapstoneProject3.jpg', '"UNIDOS will be an app that will function as the user’s personal guide with what is the DACA process. It will provide all the help they may need with the applications, list of paperwork, important dates, anything needed to get through this journey successfully. It will also provide many other useful resources and features that will be beneficial to all latino students currently under DACA.'],
['Alex Bang', 'title', 'img1', 'img2', 'img3', 'description'],
['Alex Inokuchi-Garvin', 'title', 'img1', 'img2', 'img3', 'description'],
['Alexis Joseph', 'title', 'img1', 'img2', 'img3', 'description'],
['Alexis De la Torre', 'title', 'img1', 'img2', 'img3', 'description'],
['Alyssa Cortez', 'The Green House Project', 'img1', 'img2', 'img3', 'Our planet has been facing an environmental crisis for a while now but in more recent years it seems to have gotten worse, we need to make a behavioral change and adopt more sustainable and environmentally friendly ways of living. There needs to be an easier way for people to access information on environmentally friendly products and that will slowly encourage them to live greener lifestyles. The Green House Project campaign plans to educate using print design which will then drive people to visit its website that hosts a “green living” challenge. The website will also feature concise information on the plastic crisis and recommend a list of ten eco-friendly personal care products visitors can switch over to.'],
['Ameer Razman Chin', 'title', 'img1', 'img2', 'img3', 'description'],
['Amy Lau', 'Alvie: your fridge assistant', 'images/Amy_Lau/amy_lau_capstoneproject1', 'images/Amy_Lau/amy_lau_capstoneproject2', 'images/Amy_Lau/amy_lau_capstoneproject3', '$160 billion worth of food gets wasted every year. Alvie is a camera and app duo that lets you manage your food in a simple manner. Save your food from going bad and be on your way to a healthier diet. Features include getting notifications on expiring foods, viewing your fridge from anywhere, and discovering recipes based on what’s available in your fridge.'],
['Angela Feng', 'title', 'img1', 'img2', 'img3', 'description'],
['Angela Gabriel', 'title', 'img1', 'img2', 'img3', 'description'],
['Ashley O\'Brien', 'title', 'img1', 'img2', 'img3', 'description'],
['Brett McCormack', 'Jam Cam', 'IMG_0186.PNG', 'Screen Shot 2020-04-07 at 8.06.37 PM.png', 'Screen Shot 2020-04-07 at 8.07.56 PM.png', 'An infrared tracking smart camera which works in junction with a software app to record audio from an instrument and video in sync. This camera will be activated whenever the user uses their instrument, and treats recording like a security camera. In other words the user has to activley save footage, instead of activley delete footage.This product would make the process of documentation a more sub-conscience process, thus allowing the user to focus more on playing their instrument.'],
['Brian Liu', 'title', 'img1', 'img2', 'img3', 'description'],
['Briana Gardener', 'Electo App: Brand Book', 'Briana_Gardener_CapstoneProject1.jpg', 'Briana_Gardener_CapstoneProject2.jpg', 'Briana_Gardener_CapstoneProject3.jpg', 'Create an engaging brand book, coherently paired with a  process explanation, for the company, Electo App, an app designed to help voters easily get informed on politicians. '],
['Calvin Smith', 'title', 'img1', 'img2', 'img3', 'description'],
['Carlos Rosas Lopez', 'Nap Pod Project', 'Juan_Rosas_CapstoneProject3.jpeg', 'Juan_Rosas_CapstoneProject7.jpeg', 'Juan_Rosas_CapstoneProject9.jpeg', 'Develop a napping pod device that would accommodate students who want to rest at the SFSU Library by better utilizing the library space. Creating this space for tired students to rest will boost their academic performance and lead to more successful students.'],
['Casey Goldman', 'title', 'img1', 'img2', 'img3', 'description'],
['Charlie Pham', 'title', 'img1', 'img2', 'img3', 'description'],
['Chayla King', 'title', 'img1', 'img2', 'img3', 'description'],
['Chengming Zhang', 'title', 'img1', 'img2', 'img3', 'description'],
['Chi ki Foo', 'title', 'img1', 'img2', 'img3', 'description'],
['Chongzhou Wang', 'title', 'img1', 'img2', 'img3', 'description'],
['Chris Bateman', 'title', 'img1', 'img2', 'img3', 'description'],
['Christian Reyes', 'title', 'img1', 'img2', 'img3', 'description'],
['Christopher Nguyen', 'title', 'img1', 'img2', 'img3', 'description'],
['Christopher Gonzalez', 'title', 'img1', 'img2', 'img3', 'description'],
['Cindy Lopez', 'title', 'img1', 'img2', 'img3', 'description'],
['Connie Mach', 'title', 'img1', 'img2', 'img3', 'description'],
['Connor Dohmen', 'title', 'img1', 'img2', 'img3', 'description'],
['Cory Vaile', 'When The Rain Falls: A Portable Packable Poncho For Emergency Weather Situations', 'Cory_Vaile_CapstoneProject1.jpg', 'Cory_Vaile_CapstoneProject2.png', 'Cory_Vaile_CapstoneProject3.jpg', 'The goal of my capstone project is to brand and develop a portable packable poncho that can be used as shelter against rain and wind. The intention of this project is to develop a reusable and packable garment that can be widely distributed to communities that would not otherwise have the funds or access to other forms of weather protection. '],
['Crisanto Dela Pena', 'title', 'img1', 'img2', 'img3', 'description'],
['Crystal Candalla', 'title', 'img1', 'img2', 'img3', 'description'],
['Dakota Clark', 'title', 'img1', 'img2', 'img3', 'description'],
['Daniel Genis', 'title', 'img1', 'img2', 'img3', 'description'],
['Daniel Chu', 'title', 'img1', 'img2', 'img3', 'description'],
['Daniela Cabezas', 'SCOUTO', 'images/Daniela_Cabezas/daniela_cabezas_capstoneproject1.jpg', 'images/Daniela_Cabezas/daniela_cabezas_capstone2.jpg', 'images/Daniela_Cabezas/daniela_cabezas_capstone3.jpg', 'My Capstone project is an app for photographers to search for new photography locations. The photographers will be able to search for different locationsdepending on scenery. Each locations will have different reviews fromother people who have shot portaits in the same location allowing forusers to depend on their review. The app opens up with a popup of afriendly reminder that we share the land with other reminding the userto be enivronmental friendly.'],
['Daniela Alcaraz', 'title', 'img1', 'img2', 'img3', 'description'],
['David Matthew Sanchez', 'Girlfriend\'s Dad', 'img1', 'img2', 'img3', 'My project is creating a brand and online space to collaborate with queer artists to produce unique queer apparel. It will be a way for the queer community to be given proper representation and credit for our unique designs and ideas. For the designs I produce myself, I will donate a portion of the proceeds to a queer origination to ensure a portion is being given back to the queer community.'],
['Dean Cohen', 'title', 'img1', 'img2', 'img3', 'description'],
['Delmy Cordon', 'title', 'img1', 'img2', 'img3', 'description'],
['Devan Ponce', 'title', 'img1', 'img2', 'img3', 'description'],
['Dezza Vidrio', 'title', 'img1', 'img2', 'img3', 'description'],
['Dominika Laukova', 'title', 'img1', 'img2', 'img3', 'description'],
['Edilson Diaz', 'title', 'img1', 'img2', 'img3', 'description'],
['Edward Bond', 'title', 'img1', 'img2', 'img3', 'description'],
['Elaina Keegan', 'title', 'img1', 'img2', 'img3', 'description'],
['Esther Chin', 'title', 'img1', 'img2', 'img3', 'description'],
['Fernando Maldonado', 'title', 'img1', 'img2', 'img3', 'description'],
['Francisco Tapia', 'title', 'img1', 'img2', 'img3', 'description'],
['Gabriela Pasquini', 'title', 'img1', 'img2', 'img3', 'description'],
['Gabrielle Kop', 'title', 'img1', 'img2', 'img3', 'description'],
['Hayden Wolf', 'title', 'img1', 'img2', 'img3', 'description'],
['Iversander Marroquin', 'title', 'img1', 'img2', 'img3', 'description'],
['Jack Tenley', 'title', 'img1', 'img2', 'img3', 'description'],
['Jake Smit', 'title', 'img1', 'img2', 'img3', 'description'],
['Jason Appler', 'title', 'img1', 'img2', 'img3', 'description'],
['Jasper Salomon', 'title', 'img1', 'img2', 'img3', 'description'],
['Jaynie Angelique Batin', 'title', 'img1', 'img2', 'img3', 'description'],
['Jenna M. Stamm', 'title', 'img1', 'img2', 'img3', 'description'],
['Jesse Vo', 'title', 'img1', 'img2', 'img3', 'description'],
['Jessica Noriega', 'title', 'img1', 'img2', 'img3', 'description'],
['Jesus Calderon', 'title', 'img1', 'img2', 'img3', 'description'],
['Jesus Negrete', 'title', 'img1', 'img2', 'img3', 'description'],
['Johnathon Tott-Berger', 'Admirari Magazine', 'Johnathon_Tott-Berger_CapstoneProject1.jpg', 'Johnathon_Tott-Berger_CapstoneProject2.jpg', 'Johnathon_Tott-Berger_CapstoneProject3.jpg', 'According to Latin–Dictionary.Net, Admirari is derived from Latin and means; to admire or respect, to be surprised at or astonished, and to regard with wonder or wonder at. The intent of Admirari Magazine is to create a dialogue between its users and the world highlighting aspects of life that affect us all. The current edition, the first of three that come out quarterly, focuses on human memory and discusses the processes behind memory formation and how our ability to remember details from our day to day life can benefit but also harm us. Admirari also has a blog post where subscribers and random users are asked to join in on the conversation and help develop topics for future editions offering our users an alternate way to engage with and influence the magazine. '],
['Jonathan Ogata', 'title', 'img1', 'img2', 'img3', 'description'],
['Jonathan Camacho', 'Public Works Campaign ', 'SeniorCapstoneMockup1.jpg', 'SeniorCapstoneMockup1.jpg', 'CAPSTONEMockup2.jpg', 'Initially, my senior project was to create a campaign to support the implementation of a high-speed rail for California. The reason I chose this direction was because of various solutions to problems like highway congestions, flight delays, and reducing our carbon footprint. My goal for this new direction was influenced by the lack of funds needed for the completion of the speed-rail project. While dealing with a global pandemic getting those proper funds doesn’t seem plausible at the time so I am proposing to redirect that money for public works projects in hopes to start rebuilding our future now. I’m creating a persuasive campaign with this new proposal while roads are clear of traffic and unemployment is rising.'],
['Jonny Ogata', 'title', 'img1', 'img2', 'img3', 'description'],
['Juliana Cacciaroni', 'title', 'img1', 'img2', 'img3', 'description'],
['Karina Zalac', 'Climate Creative: 7x7 Project', 'images/Karina_Zalac/Karina_Zalac_CapstoneProject1.jpg', 'images/Karina_Zalac/Karina_Zalac_CapstoneProject2.jpg', 'images/Karina_Zalac/Karina_Zalac_CapstoneProject3.jpg', 'This study seeks to assist Climate Creative in their efforts at designing sustainable solutions to combat climate change. To achieve this, Climate Creative is looking to host an event that will raise funds and gather creatives to collaborate on projects. By bringing more creative individuals together, the impact will be much more significant. Researching how to effectively market and campaign Climate Creative’s event is crucial to the success of this study.'],
['Katherine Berg', 'title', 'img1', 'img2', 'img3', 'description'],
['Kenny Ngo', 'Planet', 'Kenny_Ngo_CapstoneProject1.jpg', 'Kenny_Ngo_CapstoneProject2.jpg', 'Kenny_Ngo_CapstoneProject3.jpg', 'My project tackles San Francisco State University student procrastination more from an emotional perspective rather than from a time-management perspective. While this project poses many challenges, like procrastination itself for me, I\'m rather excited to see the outcome! '],
['Kevin Lambert', 'CoGrow', 'images/Kevin_Lambert/Kevin_Lambert_ThirdProject1.jpg', 'images/Kevin_Lambert/Kevin_Lambert_ThirdProject2.jpg', 'images/Kevin_Lambert/Kevin_Lambert_ThirdProject3.jpg', 'CoGrow is a community agriculture network that democratizes the farm-to-table social movement. Consumed mainly through a digital app and a customized gardening starter kit, CoGrow pairs users with a compatible crop for them to nurture, with the goal of growing along side others on the CoGrow social network, sharing tips and doing meetup events.'],
['Khang Hoang', 'title', 'img1', 'img2', 'img3', 'description'],
['Korina Moreno', 'title', 'img1', 'img2', 'img3', 'description'],
['Kristy Chi', 'title', 'img1', 'img2', 'img3', 'description'],
['Kwanwu Yu', 'title', 'img1', 'img2', 'img3', 'description'],
['Kyle Millhollin', 'title', 'img1', 'img2', 'img3', 'description'],
['Lauren Pattugalan', 'title', 'img1', 'img2', 'img3', 'description'],
['Lauren Hohls', 'title', 'img1', 'img2', 'img3', 'description'],
['Leilani Paz', 'title', 'img1', 'img2', 'img3', 'description'],
['Lemuel Manalo', 'title', 'img1', 'img2', 'img3', 'description'],
['Linda Lueng', 'title', 'img1', 'img2', 'img3', 'description'],
['Lois Chen', 'title', 'img1', 'img2', 'img3', 'description'],
['Madison Macha', 'title', 'img1', 'img2', 'img3', 'description'],
['Mahya Lewis', 'title', 'img1', 'img2', 'img3', 'description'],
['Mariana De Araujo Souto', 'title', 'img1', 'img2', 'img3', 'description'],
['Mariantonia Cambareri', 'title', 'img1', 'img2', 'img3', 'description'],
['Marielle Cabillo', 'SOL Kit: Anxiety Edition', 'Marielle_Cabillo_CapstoneProject1.jpg', 'Marielle_Cabillo_CapstoneProject2.jpg', 'Marielle_Cabillo_CapstoneProject3.jpg', 'For my senior project, I created a kit of three different card games young adults can play with their parents. The objectives of the games are to normalize anxiety, show how negative mindsets can be detrimental to one\'s mental health, and to present different ways one can soothe and manage their anxiety better. This kit aims to bridge the generational gap when it comes to the understanding and destigmatization of mental health issues.'],
['Mary Motley', 'title', 'img1', 'img2', 'img3', 'description'],
['Mattie Nye', 'title', 'img1', 'img2', 'img3', 'description'],
['Mauricio Morazan Mejia', 'SF State Gateway Webpage', 'img1', 'img2', 'img3', 'The SF State Gateway provides online access to see news highlights about campus events, articles and live bus schedule from Muni, also on Gateway, you have access to the student center where you can enroll for classes, make payment, check on financial aid status and order official SF State Transcript. Students from SF State have a problem navigating to the SF State Gateway page, some of the issues that students faces on Gateway is accessing the pages are problematic, when you sign in, you have to pass with many pages to get into the student center and this issue students felt it kind of annoying to do by opening many pages to go on what i want, also the page seens blank because on the main page provides a a news section where student skip by go on the student center, so for this project i would like to improve the SF State main page to provide a new interface were you can access the latest news and events dates from the campus and a place where you can find campus resources, live bus schedule, and a call of action button to access the student center easier on the SF State Gateway.'],
['Max Kolden', 'title', 'img1', 'img2', 'img3', 'description'],
['Maxwell Lohr', 'title', 'img1', 'img2', 'img3', 'description'],
['Mia Dong', 'title', 'img1', 'img2', 'img3', 'description'],
['Michael Ihle', 'MTP (Multifunctional Travel Pack)', 'img1', 'img2', 'img3', 'The Bait Shop’s MTP is a unique, multi-functioning bag created for anyone from the urban dweller to any mountain person alike. The goal is to create a perfect cross over, a bag that’s a jacket and a jacket that’s a bag. The driving factor behind this project is convenience. To have two useful everyday products In one. It will limit the things you need to bring everyday and also limit the things you need to buy.'],
['Michelle Nam', 'title', 'img1', 'img2', 'img3', 'description'],
['Monica Chum', 'San Mateo County Court Website Redesign', 'img1', 'img2', 'img3', 'For many government websites, each page is an information overload. Users are immediately confronted with a plethora of options, texts, links, and hard-to-read gradient buttons. And that’s only the first page. The San Mateo County Court website is no exception. Their use of hierarchy, color, text size, and layout is poor, making tasks much harder to complete. Even for more skilled web users, it’s a difficult website to get around. I really wanted to explore the user experience and website accessibility of government websites in this project.'],
['Natasha Sherbaf', 'title', 'img1', 'img2', 'img3', 'description'],
['Nicolas Noratto', 'title', 'img1', 'img2', 'img3', 'description'],
['Nik Dommen', 'title', 'img1', 'img2', 'img3', 'description'],
['Niklaus Dommen', 'title', 'img1', 'img2', 'img3', 'description'],
['Noah Castro', 'title', 'img1', 'img2', 'img3', 'description'],
['Nora Kettles', 'title', 'img1', 'img2', 'img3', 'description'],
['Omar Hernandez', 'title', 'img1', 'img2', 'img3', 'description'],
['Pablo Wu', 'title', 'img1', 'img2', 'img3', 'description'],
['Pamela Liutama', 'title', 'img1', 'img2', 'img3', 'description'],
['Paramveer Singh', 'title', 'img1', 'img2', 'img3', 'description'],
['Rachel Ward', 'title', 'img1', 'img2', 'img3', 'description'],
['Regine Ong', 'title', 'img1', 'img2', 'img3', 'description'],
['Rexford Adams', 'title', 'img1', 'img2', 'img3', 'description'],
['Roberto Berrocal-Pujol', 'STASHelf', 'Roberto_Berrocal-Pujol_STASHelf 1.jpg', 'Roberto_Berrocal-Pujol_STASHelf 2.jpg', 'Roberto_Berrocal-Pujol_STASHelf 3.jpg', 'Regular looking desktop cabinet with upper smell proof storage compartment, refrigeration for infused products and 3 humidifier drawers for cannabis flowers or tobacco products, for privacy and discretion for Medicinal Cannabis Patients, recreational users and any other prescription in-between. My generation was brought up either by traditionalists or Baby Boomers, who’s experience of 80 years of prohibition yields as a result a very intolerant outlook towards medical cannabis, and even worse for recreational use. Laws have changed, but the attitude and opinion of my parent’s generation and my Grandparents generation is that of substantial unease. This is the juncture where STASHelf comes about, the need of discretion of a generation that has had herbal medicinal justice served, but out of respect to our parents and grandparents we don’t want to have them see our paraphernalia or any other medical marihuana product. Because every iteration of such an event since adolescence has always had the same outcome of “Reefer Madness” traumatized (scared straight) generations.'],
['Ryan Bach', 'title', 'img1', 'img2', 'img3', 'description'],
['Ryan Spalding', 'title', 'img1', 'img2', 'img3', 'description'],
['Sabrina Umbay', 'title', 'img1', 'img2', 'img3', 'description'],
['Samuel Vasquez', 'title', 'img1', 'img2', 'img3', 'description'],
['Sarina Campanella', 'Mood App', 'Mood_submit.png', 'Mood_submit2.png', 'Mood-Submit3.png', 'Mood is a smartphone app that is created for those wishing to improve their mental health using cognitive chromatherapy, also known as color psychology. This is implemented through a profile-based tracking system for a user’s mood while also displaying colors and scenes that are known to relieve stress, anxiety, or improve energy. The app also uses positive affirmations to encourage building optimistic behavioral patterns. This includes providing mental health resources to actual doctors, or hotlines.  '],
['Sean Huang', 'O- Fred  Stove Safety Device', 'img1', 'img2', 'img3', 'O- Fred <br> A stove top converter that converts house hold stove top to a smart kitchen stove.Preventing potential house hold fire from being distracted by busy life, or not being able to react due to physical disability."'],
['Shaine Edmond', 'title', 'img1', 'img2', 'img3', 'description'],
['Shea O\'Sullivan', 'Collective', 'Shea_Osullivan_CapstoneProject1.jpeg', 'Shea_Osullivan_CapstoneProject2.jpeg', 'Shea_Osullivan_CapstoneProject3.jpeg', 'Collective is a platform where artists and designers can connect, gain visibility, and build community. The website connects users by location and provides a simple graphic tee shirt gallery, a buy sell trade feature, and message, critique and discussion boards. All artwork in these mockups are my own artwork but the final mockups will be artwork by other local artists. '],
['Tanya Hosseiny', 'title', 'img1', 'img2', 'img3', 'description'],
['Tarrea Tolbert', 'title', 'img1', 'img2', 'img3', 'description'],
['Taylor Bosch', 'title', 'img1', 'img2', 'img3', 'description'],
['Thomas Kim', 'title', 'img1', 'img2', 'img3', 'description'],
['Timothy Green', 'title', 'img1', 'img2', 'img3', 'description'],
['Tjark Riddle', 'title', 'img1', 'img2', 'img3', 'description'],
['Tony Li', 'Future on career and interview’s success', 'images/Tony_Li/Tony_Li_Tony_Li_CapstoneProject1.jpg', 'images/Tony_Li/Tony_Li_Tony_Li_CapstoneProject2.jpg', 'images/Tony_Li/Tony_Li_Tony_Li_CapstoneProject3.jpg', 'My senior design project is going to design the app for SFSU students to help them find a career after they graduate and mock an interview. And the app the name called it "Dream Bird". Students can use the app to post forum to in the app and mock an interview with each other.'],
['Travis Marr', 'title', 'img1', 'img2', 'img3', 'description'],
['Tyler Browne', 'title', 'img1', 'img2', 'img3', 'description'],
['Victoria Dai', 'title', 'img1', 'img2', 'img3', 'description'],
['Vincent Lim', 'title', 'img1', 'img2', 'img3', 'description'],
['Vy Nguyen', 'title', 'img1', 'img2', 'img3', 'description'],
['Wei Wei Lin', 'title', 'img1', 'img2', 'img3', 'description'],
['Wen Liang', 'title', 'img1', 'img2', 'img3', 'description'],
['Wilson Lee', 'title', 'img1', 'img2', 'img3', 'description'],
['Winnie Manyin Guan', 'title', 'img1', 'img2', 'img3', 'description'],
['Winta Semere', 'title', 'img1', 'img2', 'img3', 'description'],
['Yancy Martinez', 'title', 'img1', 'img2', 'img3', 'description'],
['Yumiko Inoue', 'title', 'img1', 'img2', 'img3', 'description'],
['Zhihui Zhang', 'title', 'img1', 'img2', 'img3', 'description'],
]

function getStudentProj3Title() {
    return studentProject3Details[designatedStudent][1];
}

function getStudentProj3Images() {
    text = '<img class="myImg" src="' + studentProject3Details[designatedStudent][2] + '">';
    text += '<img class="myImg" src="' + studentProject3Details[designatedStudent][3] + '">';
    if (studentProject3Details[designatedStudent][4] !== '') {
    	text += '<img class="myImg" src="' + studentProject3Details[designatedStudent][4] + '">';
    }
    return text;
}

function getStudentProj3Description() {
    return studentProject3Details[designatedStudent][5];
}